FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# RS216_APIARY

API to add two numbers.

## Add Collection [/add]

### Addition of two numbers [GET]

+ Parameters
    + in1: 2
    + in2: 8

+ Response 200 (application/json)

        [
            {
                "result": "10"
            }
        ]